var img;
var arrowAway;
var arrowTowards;
var arrowRight;
var arrowLeft;
var arrowDown;
var arrowUp;
var n0;
var n1;
var n2;
var n3;
var n4;
var n5;
var n6;
var n7;
var n8;
var n9;
var d0;
var d1;
var d2;
var d3;
var d4;
var d5;
var d6;
var d7;
var d8;
var d9;
var A;
var B;
var C;
var D;
var E;
var F;
var check;
var cross;

function setup() {
    createCanvas(window.innerWidth,window.innerHeight);
    img = loadImage('https://i.imgur.com/6oUoU7N.jpg');
    arrowAway = loadImage('https://i.imgur.com/HZBSw6S.jpg');
    arrowTowards  = loadImage('https://i.imgur.com/xnLoZA4.jpg');
    arrowRight = loadImage('https://i.imgur.com/1xnByw6.jpg');
    arrowLeft = loadImage('https://i.imgur.com/6S03CZc.jpg');
    arrowDown = loadImage('https://i.imgur.com/Zq8OXwa.jpg');
    arrowUp = loadImage('https://i.imgur.com/6GjwON4.jpg');
    n0 = loadImage('https://i.imgur.com/FkGoBzM.jpg');
    n1 = loadImage('https://i.imgur.com/dI9FLkO.jpg');
    n2 = loadImage('https://i.imgur.com/oT5D3Iy.jpg');
    n3 = loadImage('https://i.imgur.com/v8F34u3.jpg');
    n4 = loadImage('https://i.imgur.com/BIjal5z.jpg');
    n5 = loadImage('https://i.imgur.com/2OZDLXe.jpg');
    n6 = loadImage('https://i.imgur.com/ZFBb1FJ.jpg');
    n7 = loadImage('https://i.imgur.com/ovEFOr8.jpg');
    n8 = loadImage('https://i.imgur.com/gcJPkTc.jpg');
    n9 = loadImage('https://i.imgur.com/98gdxBg.jpg');
    d0 = loadImage('https://i.imgur.com/NPdpsqQ.jpg');
    d1 = loadImage('https://i.imgur.com/YS1OugL.jpg');
    d2 = loadImage('https://i.imgur.com/b8vqFjP.jpg');
    d3 = loadImage('https://i.imgur.com/eN9XPge.jpg');
    d4 = loadImage('https://i.imgur.com/t8zq5tm.jpg');
    d5 = loadImage('https://i.imgur.com/MfAnYbH.jpg');
    d6 = loadImage('https://i.imgur.com/s1CQg1u.jpg');
    d7 = loadImage('https://i.imgur.com/fng77t5.jpg');
    d8 = loadImage('https://i.imgur.com/n16M8ct.jpg');
    d9 = loadImage('https://i.imgur.com/Evn0NXV.jpg');
    A = loadImage('https://i.imgur.com/Hje3VdQ.png');
    B = loadImage('https://i.imgur.com/ph4G1xX.png');
    C = loadImage('https://i.imgur.com/HwYIllF.png');
    D = loadImage('https://i.imgur.com/l5JozyG.png');
    E = loadImage('https://i.imgur.com/Do8S7tj.png');
    F = loadImage('https://i.imgur.com/BylYOOl.png');
    check = loadImage('https://i.imgur.com/mPrSog5.jpg');
    cross = loadImage('https://i.imgur.com/TMagLJm.jpg');
}
